### ISSUE TITLE
Build script fails with p4est_jll 2.8.0

### ISSUE THREAD

**Issue by JordiManyer** [gridap/p4est_wrapper.jl#15]
```
ERROR: Error building `P4est_wrapper`: 
ERROR: LoadError: UndefVarError: artifact_dir not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ ~/.julia/packages/P4est_wrapper/zSIB0/deps/build.jl:9
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [4] top-level scope
   @ none:5
in expression starting at /home/user1/.julia/packages/P4est_wrapper/zSIB0/deps/build.jl:4

```

**Comment by amartinhuertas** [comment]
For completeness, this problem does not arise with julia 1.7.3 and p4est_jll 2.8.0 in github actions ... see https://github.com/gridap/GridapP4est.jl/actions/runs/3132363053/jobs/5084628907#step:7:98 for more details.

Might it be a julia version issue? (the problem reported here was reproduced on a local machine with julia 1.8.0

**Comment by JordiManyer** [comment]
> For completeness, this problem does not arise with julia 1.7.3 and p4est_jll 2.8.0 in github actions ... see https://github.com/gridap/GridapP4est.jl/actions/runs/3132363053/jobs/5084628907#step:7:98 for more details.
> 
> Might it be a julia version issue? (the problem reported here was reproduced on a local machine with julia 1.7.8

The local machine runs julia 1.8.0

**Comment by amartinhuertas** [comment]
> The local machine runs julia 1.8.0

Correct. Thanks! Fixed.

**Comment by JordiManyer** [comment]
So I've upgraded the Julia binaries to 1.8.1 and the problem seems to be fixed.... Now everything builds OK while having `P4est_jll 2.8.0`. So it was a Julia problem.

**Comment by amartinhuertas** [comment]
Added issue to known issues section of README.md file. Closing this issue ...
