### ISSUE TITLE
Build script failes on Windows using P4est_jll artifact

### ISSUE THREAD

**Issue by zjwegert** [gridap/p4est_wrapper.jl#22]
The `build.jl` currently fails to find the libp4est library on Windows. This appears to be because [`P4est_jll`](https://github.com/JuliaBinaryWrappers/P4est_jll.jl/blob/main/src/wrappers/x86_64-w64-mingw32-mpi%2Bmicrosoftmpi.jl) creates the `.dll` files in the artifact directory bin (with a different name from `libp4st`!) and creates a `.dll.a` in in lib. The `.dll.a` files are then not recognised by `Libdl.find_library`.

A workaround is to modify `build.jl` as
```
...
if (cmp(P4EST_LIB,"") == 0)
# Check P4EST_LIB (.../libp4est.so file) exists
    P4EST_LIB = string(Libdl.find_library(P4EST_LIB_NAME,[P4EST_LIB_DIR,P4EST_ROOT_DIR]),".",Libdl.dlext)
    if P4EST_ARTIFACT && (cmp(P4EST_LIB,string(".",Libdl.dlext)) == 0) # Fix for finding dll on Windows
        P4EST_LIB = P4est_jll.get_libp4est_path()
    end
end
...
```
instead of 
```
...
if (cmp(P4EST_LIB,"") == 0)
# Check P4EST_LIB (.../libp4est.so file) exists
    P4EST_LIB = string(Libdl.find_library(P4EST_LIB_NAME,[P4EST_LIB_DIR,P4EST_ROOT_DIR]),".",Libdl.dlext)
end
...
```

**Comment by JordiManyer** [comment]
Hi @zjwegert , thanks for the issue! Unfortunately I do not have access to a windows machine, so you'll have to walk me throught it. 

My first impression is that if we are using an artifact, we probably always want to be using the function `P4est_jll.get_libp4est_path()` to find path. Unfortunately with `P4est_jll` on linux I cannot seem to have access to that function. Is it something that might be limited to some versions of the artifact? 

EDIT: It is showing now, after updating. I can also seem to have access to that function for artifacts on linux for versions 2.2-2.8 (i.e all versions supported). I'm then for using this function whenever we have an artifact.

**Comment by JordiManyer** [comment]
What do you think @amartinhuertas ?

**Comment by JordiManyer** [comment]
@zjwegert can you check the PR branch works on windows?

**Comment by zjwegert** [comment]
> @zjwegert can you check the PR branch works on windows?

Done! Works on my machine.
